#!/bin/bash

dotnet publish -c Release -r linux-x64 \
    /p:SelfContained=true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

rsync -ruavhP bin/Release/net10.0/linux-x64/publish/ $LOCIP:/home/i3ym/maks_gaming/
